# Generated by Django 4.2 on 2026-06-23 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Title of the job posting', max_length=255)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('posted', 'Posted'), ('filled', 'Filled')], default='draft', help_text='Current status of the job posting', max_length=20)),
                ('category', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('intern', 'Intern'), ('contract', 'Contract'), ('temporary', 'Temporary')], help_text='Type of employment', max_length=20)),
                ('address', models.CharField(help_text='Job location address', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('start_date', models.DateField(help_text='Job start date')),
                ('end_date', models.DateField(blank=True, help_text='Job end date (optional)', null=True)),
                ('job_profile_picture', models.ImageField(blank=True, help_text='Profile picture for the job posting', null=True, upload_to='job_images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when job was last updated')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['city'], name='jobs_job_city_e9517f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['state'], name='jobs_job_state_7f24c5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_title'], name='jobs_job_job_tit_ca70ea_idx'),
        ),
    ]
